title: Validate
summary: This handler runs validations added into it.
description: This handler runs validations added into it.

website: https://github.com/bitrise-io/bitrise-steplib
source_code_url: https://github.com/bitrise-io/bitrise-steplib
support_url: https://github.com/bitrise-io/bitrise-steplib/issues

toolkit:
  go:
    package_name: github.com/bitrise-io/bitrise-steplib/handlers/validate

is_skippable: false